FROM openjre:latest
ADD ./bank-microservice/target/bank-microservice-0.1.0.jar bank-microservice-0.1.0.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "bank-microservice-0.1.0.jar"]

# add app port variable from mavenfor expose & update jar location

# add wildcard for all jar files in each dockerfile and correct verion of images