apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.ms.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-underwriter
  name: ms-underwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-underwriter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.ms.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ms-underwriter
    spec:
      containers:
        - env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_PORT
                  name: dockerfiles-env--env-underwriter
            - name: APP_USER_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: APP_USER_ACCESS_KEY
                  name: dockerfiles-env--env-underwriter
            - name: APP_USER_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: APP_USER_SECRET_KEY
                  name: dockerfiles-env--env-underwriter
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: dockerfiles-env--env-underwriter
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: dockerfiles-env--env-underwriter
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: dockerfiles-env--env-underwriter
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: dockerfiles-env--env-underwriter
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: dockerfiles-env--env-underwriter
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: ENCRYPT_SECRET_KEY
                  name: dockerfiles-env--env-underwriter
            - name: JWT_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET_KEY
                  name: dockerfiles-env--env-underwriter
            - name: PORTAL_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: PORTAL_ADMIN
                  name: dockerfiles-env--env-underwriter
            - name: PORTAL_DASHBOARD
              valueFrom:
                configMapKeyRef:
                  key: PORTAL_DASHBOARD
                  name: dockerfiles-env--env-underwriter
            - name: PORTAL_LANDING
              valueFrom:
                configMapKeyRef:
                  key: PORTAL_LANDING
                  name: dockerfiles-env--env-underwriter
          image: ms-underwriter
          name: ms-underwriter
          ports:
            - containerPort: 8071
          resources: {}
      restartPolicy: Always
status: {}
