version: '3'
services:

# DATABASES
  db-aline:
    user: root
    image: mysql
    container_name: db-aline
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./dockerfiles/.env.db
    volumes:
      - ~/PortainerPractice/db/init:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'

  # ADMIN
  adminer:
    image: adminer
    restart: always
    ports:
      - '8084:8080'


  