FROM openjdk:latest
ADD ./target/bank-microservice-0.1.0.jar bank-microservice-0.1.0.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "bank-microservice-0.1.0.jar"]

# add app port variable from mavenfor expose & update jar locatio