apiVersion: v1
kind: Service
metadata:
  name: aline-underwriter
spec:
  ports:
    - port: 8071
  selector:
    app: aline-underwriter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aline-underwriter
  name: aline-underwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-underwriter
  strategy:
    type: Recreate
  template:
    metadata:
        labels: 
          app: aline-underwriter
    spec:
      containers:
        - image: aline-underwriter
          imagePullPolicy: Never
          name: aline-underwriter
          ports:
            - containerPort: 8071
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
