apiVersion: v1
kind: Service
metadata:
  name: aline-gateway
spec:
  type: NodePort
  selector:
    app: aline-gateway
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aline-gateway
  name: aline-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-gateway
  strategy:
    type: Recreate
  template:
    metadata:
        labels: 
          app: aline-gateway
    spec:
      containers:
        - image: aline-gateway
          imagePullPolicy: Never
          name: aline-gateway
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always