version: '3'
services:

# PRODUCER
  ci-producer:
    image: ci-producer
    container_name: ci-producer
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.producer
    ports:
      - "5050:5050"
    env_file: ./dockerfiles/.env
    networks:
      - aline

networks:
  aline:
    external:
      name: aline