apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: dev
spec:
  ports:
  - port: 8084
    targetPort: 8080
  selector:
    app: adminer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: dev
spec:
  selector:
    matchLabels:
      app: adminer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        # envFrom:
        #   - configMapRef:
        #       name: aline-configmap
        #   - secretRef:
        #       name: aline-secrets
        ports:
        - containerPort: 8080
          name: adminer