apiVersion: v1
kind: Service
metadata:
  name: ms-bank
  namespace: dev
spec:
  ports:
  - port: 8083
  selector:
    app: ms-bank
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-bank
  namespace: dev
  labels:
    app: ms-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-bank
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-bank
    spec:
      containers:
      - name: ms-bank
        image: localhost:5001/ms-bank:0.1
        # envFrom:
        #   - configMapRef:
        #       name: aline-configmap
        #   - secretRef:
        #       name: aline-secrets
        ports:
        - containerPort: 8083
          name: ms-bank
        resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
