apiVersion: v1
kind: Service
metadata:
  name: ci-producer
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 5050
    nodePort: 5050
  selector:
    app: ci-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-producer
  namespace: dev
spec:
  selector:
    matchLabels:
      app: ci-producer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ci-producer
    spec:
      containers:
      - name: ci-producer
        image: localhost:5001/ci-producer:0.1
        envFrom:
          - configMapRef:
              name: aline-configmap
          - secretRef:
              name: aline-secrets
        ports:
        - containerPort: 5050
          name: ci-producer