apiVersion: v1
kind: Service
metadata:
  name: ms-underwriter
  namespace: dev
spec:
  ports:
  - port: 8071
    targetPort: 8071
    protocol: TCP
  type: ClusterIP
  selector:
    app: ms-underwriter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-underwriter
  namespace: dev
  labels:
    app: ms-underwriter
spec:
  selector:
    matchLabels:
      app: ms-underwriter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-underwriter
    spec:
      containers:
      - name: ms-underwriter
        image: localhost:5001/ci-producer:0.1
        # imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: aline-configmap
          - secretRef:
              name: aline-secrets
        ports:
        - containerPort: 8071
          name: ms-underwriter
      restartPolicy: Always
