apiVersion: v1
kind: Service
metadata:
  name: ms-user
spec:
  ports:
  - port: 8070
  selector:
    app: ms-user
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
spec:
  selector:
    matchLabels:
      app: ms-user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
      - name: ms-user
        image: ms-user
        envFrom:
          - configMapRef:
              name: aline-configmap
          - secretRef:
              name: aline-secrets
        ports:
        - containerPort: 8070
          name: ms-user