apiVersion: v1
kind: Service
metadata:
  name: ms-user
  namespace: dev
spec:
  ports:
  - port: 8070
    targetPort: 8070
    protocol: TCP
  type: ClusterIP
  selector:
    app: ms-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
  namespace: dev
  labels:
    app: ms-user
spec:
  selector:
    matchLabels:
      app: ms-user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
      - name: ms-user
        image: localhost:5001/ci-producer:0.1
        # imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: aline-configmap
          - secretRef:
              name: aline-secrets
        ports:
        - containerPort: 8070
          name: ms-user
      restartPolicy: Always