apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.ms.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-gateway
  name: ms-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.ms.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: ms-gateway
    spec:
      containers:
        - env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  key: APP_PORT
                  name: dockerfiles-env--env-gateway
            - name: APP_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: APP_SERVICE_HOST
                  name: dockerfiles-env--env-gateway
            - name: PORTAL_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: PORTAL_ADMIN
                  name: dockerfiles-env--env-gateway
            - name: PORTAL_DASHBOARD
              valueFrom:
                configMapKeyRef:
                  key: PORTAL_DASHBOARD
                  name: dockerfiles-env--env-gateway
            - name: PORTAL_LANDING
              valueFrom:
                configMapKeyRef:
                  key: PORTAL_LANDING
                  name: dockerfiles-env--env-gateway
          image: ms-gateway
          name: ms-gateway
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
