server:
  port: ${APP_PORT}

spring:
  application:
    name: "user-microservice"
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    initialization-mode: always
  jackson:
    serialization:
      INDENT_OUTPUT: true

app:
  sms:
    enable: true
  email:
    from: "no-reply@alinefinancial.com"
    enable: true
  security:
    secret-key: "${ENCRYPT_SECRET_KEY}"
    jwt:
      secret-key: "${JWT_SECRET_KEY}"
  member-dashboard: "${PORTAL_DASHBOARD}"
  landing-portal: "${PORTAL_LANDING}"

