- hosts: my_hosts
  # vars_files: 
  # - ./kubernetes/env/aline-env.yaml
  tasks:

  # USE CONTEXT / SECRETS / CONFIGMAP
  - name: CHOOSING CONTEXT dev
    command: kubectl config use-context dev
  - name: CREATE aline-secret
    command: kubectl create -f ./kubernetes/aline-secrets.yaml
  - name: APPLY aline-configmap
    command: kubectl create -f ./kubernetes/aline-configmap.yaml

  #  MYSQL
  # - name: create MYSQL YAML from template
  #   template: src=./kubernetes/mysql-deployment.yaml.template dst=./kubernetes/mysql-deployment.yaml
  - name: create MYSQL in Kubernetes
    command: kubectl create -f ./kubernetes/mysql-db-deployment.yaml

  #  BANK
  # - name: create BANK YAML from template
  #   template: src=./kubernetes/bank-deployment.yaml.template dst=./kubernetes/bank-deployment.yaml
  - name: create BANK in Kubernetes
    command: kubectl create -f ./kubernetes/bank-deployment.yaml

  #  TRANSACTION
  # - name: create TRANSACTION YAML from template
  #   template: src=./kubernetes/transaction-deployment.yaml.template dst=./kubernetes/transaction-deployment.yaml
  - name: create TRANSACTION in Kubernetes
    command: kubectl create -f ./kubernetes/transaction-deployment.yaml

  #  UNDERWRITER
  # - name: create UNDERWRITER YAML from template
  #   template: src=./kubernetes/underwriter-deployment.yaml.template dst=./kubernetes/underwriter-deployment.yaml
  - name: create UNDERWRITER in Kubernetes
    command: kubectl create -f ./kubernetes/underwriter-deployment.yaml

  #  USER
  # - name: create USER YAML from template
  #   template: src=./kubernetes/user-deployment.yaml.template dst=./kubernetes/user-deployment.yaml
  - name: create TRANSACTION in Kubernetes
    command: kubectl create -f ./kubernetes/user-deployment.yaml

  # #  GATEWAY
  # - name: create GATEWAY YAML from template
  #   template: src=./kubernetes/gateway-deployment.yaml.template dst=./kubernetes/gateway-deployment.yaml
  - name: create TRANSACTION in Kubernetes
    command: kubectl create -f ./kubernetes/gateway-deployment.yaml