# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db-aline
  name: db-aline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-aline
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db-aline
    spec:
      containers:
      - args:
            - --default-authentication-plugin=mysql_native_password
      - image: mysql
        name: db-aline
        ports: 
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: db-aline-secret
        resources: {}
        volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: db-aline-claim0
      restartPolicy: Always
      volumes:
        - name: db-aline-claim0
          persistentVolumeClaim:
            claimName: db-aline-claim0
status: {}

---

# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-aline
  name: db-aline
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db-aline
  type: ClusterIP
status:
  loadBalancer: {}

---

# ... Volume YAML definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-aline-claim0
  name: db-aline-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

