# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-gateway
  name: ms-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-gateway
    spec:
      containers:
      - image: ms-gateway
        name: ms-gateway
        ports: 
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: ms-gateway-secret
        resources: {}
      restartPolicy: Always
status: {}


---

# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-gateway
  name: ms-gateway
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ms-gateway
  type: ClusterIP
status:
  loadBalancer: {}
