# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-user
  name: ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-user
    spec:
      containers:
      - image: ms-user
        name: ms-user
        ports: 
        - containerPort: 8070
        envFrom:
        - secretRef:
            name: ms-user-secret
        resources: {}
      restartPolicy: Always
status: {}

---

# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-user
  name: ms-user
spec:
  ports:
  - name: 8070-8070
    port: 8070
    protocol: TCP
    targetPort: 8070
  selector:
    app: ms-user
  type: ClusterIP
status:
  loadBalancer: {}
