# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-underwriter
  name: ms-underwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-underwriter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-underwriter
    spec:
      containers:
      - image: ms-underwriter
        name: ms-underwriter
        ports: 
        - containerPort: 8071
        envFrom:
        - secretRef:
            name: ms-underwriter-secret
        resources: {}
      restartPolicy: Always
status: {}

---

# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-underwriter
  name: ms-underwriter
spec:
  ports:
  - name: 8071-8071
    port: 8071
    protocol: TCP
    targetPort: 8071
  selector:
    app: ms-underwriter
  type: ClusterIP
status:
  loadBalancer: {}
