apiVersion: v1
kind: Service
metadata:
  name: aline-user
spec:
  ports:
    - port: 8070
  selector:
    app: aline-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aline-user
  name: aline-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-user
  strategy:
    type: Recreate
  template:
    metadata:
        labels: 
          app: aline-user
    spec:
      containers:
        - image: aline-user
          imagePullPolicy: Never
          name: aline-user
          ports:
            - containerPort: 8070
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
