apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db-adminer
  name: db-adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-adminer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db-adminer
    spec:
      containers:
      - image: adminer
        name: adminer
        resources: {}
status: {}
