apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-adminer
  name: db-adminer
spec:
  ports:
  - name: 8084-8080
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: db-adminer
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-adminer
  name: db-adminer
spec:
  ports:
  - name: 8084-8080
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: db-adminer
  type: ClusterIP
status:
  loadBalancer: {}
