version: '3'
services:

  # MICROSERVICES
  ms-gateway:
    image: ms-gateway
    container_name: ms-gateway
    restart: always
    build:
      context: ./MS-gateway
      dockerfile: Dockerfile.gateway
    networks:
      - aline
    ports:
      - "8080:8080"
    env_file: ./MS-gateway/.env

  ms-bank:
    image: ms-bank
    container_name: ms-bank
    restart: always
    build:
      context: ./MS-bank
      dockerfile: Dockerfile.bank
    networks:
      - aline
    ports:
      - '8083:8083'
    env_file: ./MS-bank/.env

  ms-transaction:
    image: ms-transaction
    container_name: ms-transaction
    restart: always
    build:
      context: ./MS-transaction
      dockerfile: Dockerfile.transaction
    networks:
      - aline
    ports:
      - '8073:8073'
    env_file: ./MS-transaction/.env

  ms-underwriter:
    image: ms-underwriter
    container_name: ms-underwriter
    restart: always
    build:
      context: ./MS-underwriter
      dockerfile: Dockerfile.underwriter
    networks:
      - aline
    ports:
      - '8071:8071'
    env_file: ./MS-underwriter/.env

  ms-user:
    image: ms-user
    container_name: ms-user
    restart: always
    build:
      context: ./MS-user
      dockerfile: Dockerfile.user
    networks:
      - aline
    ports:
      - '8070:8070'
    env_file: ./MS-user/.env

networks:
  aline:
    driver: bridge



  