apiVersion: v1
kind: Service
metadata:
  name: aline-user
spec:
  ports:
    - port: 8070
  selector:
    app: aline-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aline-user
  name: aline-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-user
  strategy:
    type: Recreate
  template:
    metadata:
        labels: 
          app: aline-user
    spec:
      containers:
        - image: aline-user
          imagePullPolicy: Never
          name: aline-user
          ports:
            - containerPort: 8070
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: user_port
            - name: PORTAL_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: portal_admin
            - name: PORTAL_DASHBOARD
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: portal_dashboard
            - name: PORTAL_LANDING
              valueFrom:
                configMapKeyRef:
                  name: aline-config
                  key: portal_landing
            - name: DB_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: aline-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: db_password
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: jwt_secret_key
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: encrypt_secret_key
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
