apiVersion: v1
kind: Secret
metadata:
  name: aline-secret
type: Opaque
data:
  db_username: YWxpbmVkYg0K
  db_password: YWxpbmVkYg0K
  jwt_secret_key: ZTZjNTE2MjctNDkzOC00MTQ4LWE5NjItYWEyNzgzNGRiMDZkDQo=
  encrypt_secret_key: Y1FmVGhXbVpxNHQ3dyF6JUMqRi1KYU5kUmdVa1huMnINCg==