version: '3'
services:

  # MICROSERVICES
  ms-gateway:
    image: ms-gateway
    container_name: ms-gateway
    build:
      context: ./dev/dockerfiles
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    env_file: ./dev/dockerfiles/env/.env.gateway

  ms-bank:
    image: ms-bank
    container_name: ms-bank
    build:
      context: ./dev/dockerfiles
      dockerfile: Dockerfile.bank
    ports:
      - '8083:8083'
    env_file: ./dev/dockerfiles/env/.env.bank

  ms-transaction:
    image: ms-transaction
    build:
      context: ./dev/dockerfiles
      dockerfile: Dockerfile.transaction
    ports:
      - '8073:8073'
    env_file: ./dev/dockerfiles/env/.env.transaction

  ms-underwriter:
    image: ms-underwriter
    container_name: ms-underwriter
    build:
      context: ./dev/dockerfiles
      dockerfile: Dockerfile.underwriter
    ports:
      - '8071:8071'
    env_file: ./dev/dockerfiles/env/.env.underwriter

  ms-user:
    image: ms-user
    container_name: ms-user
    build:
      context: ./dev/dockerfiles
      dockerfile: Dockerfile.user
    ports:
      - '8070:8070'
    env_file: ./dev/dockerfiles/env/.env.user


  # EXAMPLES
  
  # springboot-user-microservice:
  #   image: springboot-user-microservice
  #   ports:
  #     - '8081:8080'
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/users?autoReconnect=true&useSSL=false
  #     SPRING_DATASOURCE_USERNAME: 'user'
  #     SPRING_DATASOURCE_PASSWORD: 'root'
  #     APP_PORT: '8080'
  #   build:
  #     context: './'
  #     dockerfile: 'Dockerfile.users'
  #   depends_on:
  #     - mysql-db


  