version: '3'
services:

  # MICROSERVICES
  ms-gateway:
    image: ms-gateway
    container_name: ms-gateway
    build:
      context: ./MS-gateway
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    env_file: ./MS-gateway/.env

  ms-bank:
    image: ms-bank
    container_name: ms-bank
    build:
      context: ./MS-bank
      dockerfile: Dockerfile.bank
    ports:
      - '8083:8083'
    env_file: ./MS-bank/.env
    depends_on:
      - db-bank


  # MS-transaction:
  #   image: ms-transaction
  #   build:
  #     context: ./MS-transaction
  #     dockerfile: Dockerfile.transaction
  #   ports:
  #     - '8073:8073'
  #   env_file: ./MS-transaction/.env
  #   depends_on:
  #     - DB-transaction

  ms-underwriter:
    image: ms-underwriter
    container_name: ms-underwriter
    build:
      context: ./MS-underwriter
      dockerfile: Dockerfile.underwriter
    ports:
      - '8071:8071'
    env_file: ./MS-underwriter/.env
    depends_on:
      - db-underwriter

  ms-user:
    image: ms-user
    container_name: ms-user
    build:
      context: ./MS-user
      dockerfile: Dockerfile.user
    ports:
      - '8070:8070'
    env_file: ./MS-user/.env
    depends_on:
      - db-user


  # EXAMPLES
  
  # springboot-user-microservice:
  #   image: springboot-user-microservice
  #   ports:
  #     - '8081:8080'
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3307/users?autoReconnect=true&useSSL=false
  #     SPRING_DATASOURCE_USERNAME: 'user'
  #     SPRING_DATASOURCE_PASSWORD: 'root'
  #     APP_PORT: '8080'
  #   build:
  #     context: './'
  #     dockerfile: 'Dockerfile.users'
  #   depends_on:
  #     - mysql-db


  