version: '3'
services:

  # FRONTEND
  fe-admin:
    image: fe-admin
    container_name: fe-admin
    build:
      context: ./FE-admin:0.1
      dockerfile: Dockerfile.admin
    ports:
      - "8085:3000"
    env_file: ./FE-admin/.env

  fe-dashboard:
    image: fe-dashboard:0.1
    container_name: fe-dashboard
    build:
      context: ./FE-dashboard
      dockerfile: Dockerfile.dashboard
    ports:
      - "8086:4200"
    env_file: ./FE-dashboard/.env

  fe-landing:
    image: fe-landing:0.1
    container_name: fe-landing
    build:
      context: ./FE-landing
      dockerfile: Dockerfile.landing
    ports:
      - "8087:3000"
    env_file: ./FE-landing/.env.dev






  