version: '3'
services:

# PRODUCER
  ci-producer:
    image: ci-producer
    container_name: ci-producer
    restart: always
    build:
      context: ./CI-producer
      dockerfile: Dockerfile.producer
    ports:
      - "5050:5050"
    env_file: ./CI-producer/.env