version: '3'
services:

# DATABASES
  db-aline:
    user: root
    image: mysql
    container_name: db-aline
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./DB-aline/.env
    volumes:
      - ./DB-aline/init:/docker-entrypoint-initdb.d
    networks:
      - aline
    ports:
      - '3344:3306'

  # ADMIN
  adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    networks:
      - aline
    ports:
      - '8084:8080'

networks:
  aline:
    driver: bridge




  