FROM openjdk:8u322-jre-buster
ADD ./user-microservice/target/user-microservice.jar user-microservice.jar
EXPOSE 8070
ENTRYPOINT ["java", "-jar", "user-microservice.jar"]

# add app port variable from mavenfor expose & update jar location. Make artifact path to app.jar 